main: de.miraculixx.headifier.HeadifierPaper
name: Headifier
description: Block Headifier - Turn solid Blocks into minified heads
version: 1.0.0
api-version: 1.16
libraries:
  - "net.axay:kspigot:1.19.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.6.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.0"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
  - "io.ktor:ktor-client-core-jvm:2.1.3"
  - "io.ktor:ktor-client-cio-jvm:2.1.3"